apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: {{ .Values.app }}
  externalName: {{ .Values.app }} 
  type: "NodePort"
  ports:
{{- range .Values.ports }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
{{- end }}
  
