apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      track: stable
  template:
    metadata:
      labels:
        app: manager
        track: stable
    spec:
      containers:
        - name: manager
          image: ghcr.io/bluedotiya/web_crawler/manager:microservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80