# Default values for manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app: "manager"
image: "manager:dev"
imagePullPolicy: "Never"

ports: 
  - containerPort: 80
  - containerPort: 5678 # Debug Port TODO REMOVE