apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder
  labels:
    app: feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
      track: stable
  template:
    metadata:
      labels:
        app: feeder
        track: stable
    spec:
      containers:
        - name: feeder
          image: ghcr.io/bluedotiya/web_crawler/feeder:microservice
          ports:
            - containerPort: 80