apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.neo4j.name }}-expose
  labels:
    app.kubernetes.io/name: {{ .Values.neo4j.name }}-expose
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
  {{- range .Values.ports }}
    - port: {{ .containerPort }}
      nodePort: {{ .nodeport }} 
      name: {{ .name }}
  {{- end }}    

  selector:
    app: {{ .Values.neo4j.name }}