# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  {{- $map:= first .Values.ports }}
    - port: {{ $map.containerPort }}
      targetPort: {{ $map.containerPort }}
      protocol: TCP
      name: bolt
  selector:
    app.kubernetes.io/name: {{ .Values.app }}