# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.app }}-svc
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app }}
  podManagementPolicy: OrderedReady
  updateStrategy:
        type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          {{- $map:= first .Values.ports }}
            - name: {{ .Values.app }}
              containerPort: {{ $map.containerPort }}
      volumes:
      {{- range .Values.PV }}
      {{- if eq .kind "PersistentVolumeClaim" }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
      {{- end }}
      {{- end }}
        - name: {{ .Values.app }}-etc-config
          configMap:
            name: {{ .Values.app }}-config