# Default values for memgraph-lab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app: "memgraph-lab"
image: "ghcr.io/bluedotiya/web_crawler/frontend:microservice"
imagePullPolicy: "IfNotPresent"

ports:
  -
    name: "vnc-over-http"
    protocol: "TCP"
    port: 6901
    targetPort: 6901
    nodePort: 32001
  -
    name: "vnc"
    protocol: "TCP"
    port: 5901
    targetPort: 5901
    nodePort: 32002
