apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /storage/local-storage-3
    type: DirectoryOrCreate