apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder
  labels:
    app.kubernetes.io/name: feeder
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 5
  selector:
    matchLabels:
      app: feeder
      track: stable
  template:
    metadata:
      labels:
        app: feeder
        track: stable
    spec:
      containers:
        - name: feeder
          image: ghcr.io/bluedotiya/web_crawler/feeder:microservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 5678 # TODO REMOVE THIS LINE Debugging