apiVersion: v1
kind: Service
metadata:
  name: feeder
  labels:
    app.kubernetes.io/name: feeder
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    name: feeder
  selector:
    app: feeder