apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports: 
  {{- range .Values.ports }} 
    - name: port-{{ .containerPort }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }} 
  {{- end }}    
  selector:
    app: {{ .Values.app }}