apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  ports: 
  {{- range .Values.ports }}
    - port: {{ .containerPort }}
      containerPort: {{ .containerPort }}
  {{- end }}  
  selector:
    app: {{ .Values.app }}