apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: headless-vnc
    app.kubernetes.io/managed-by: Helm
  name: headless-vnc
spec:
  externalName: headless-vnc
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 6901
    targetPort: 6901
    nodePort: 32001
  - name: vnc-port-tcp
    protocol: TCP
    port: 5901
    targetPort: 5901
    nodePort: 32002
  selector:
    app: headless-vnc
  type: NodePort
