apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports: 
  {{- $map:=first .Values.ports }}
    - port: {{ $map.containerPort }}
      targetPort: {{ $map.containerPort }} 
  name: {{ .Values.app }}
  selector:
    app: {{ .Values.app }}