apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports: 
  {{- range .Values.ports }}
    - port: {{ .containerPort }}
      nodePort: {{ .nodeport }} 
      name: {{ .name }}
  {{- end }}  
  selector:
    app: {{ .Values.app }}