apiVersion: v1
kind: Service
metadata:
  name: manager
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    name: manager
  selector:
    app: manager